### ISSUE TITLE
Chart never loads when I follow link "What products are feasible for Colombia in 2013" from splash page

### ISSUE THREAD

**Issue by gregshap** [cid-harvard/atlas-economic-complexity#345]
When I go to http://atlas.cid.harvard.edu/ and click the "What products are feasible for Colombia in 2013" link, it takes me to http://atlas.cid.harvard.edu/explore/pie_scatter/export/col/all/show/2013/.

This page never loads: there's a js console error and a 500 error from one of the api calls

**Comment by makmanalp** [comment]
Fixed, caused by unpushed deployment script changes
