### ISSUE TITLE
Deflator for 2013 data is missing

### ISSUE THREAD

**Issue by romsson** [cid-harvard/atlas-economic-complexity#349]
For constant and per capita constant options

![screen shot 2015-05-19 at 10 20 16 am](https://cloud.githubusercontent.com/assets/586236/7705191/c9539c1a-fe10-11e4-81cb-e5e804b008bb.png)

**Comment by gregshap** [comment]
Fixed by uploading correct deflators: http://atlas.cid.harvard.edu/explore/stacked/export/vnm/all/show/1995.2013.2/?prod_class=hs4&details_treemap=2&disable_widgets=false&disable_search=false&node_size=none&queryActivated=true&highlight=&yaxis=current

**Comment by makmanalp** [comment]
@gregshap nope, check out "constant" and "per capita constant"
